DatabaseDsn: "host=0.0.0.0 user=sajjad password=sajjad123 dbname=postgres port=5435 TimeZone=UTC"
DatabaseDisable: true

HTTPServerReadTimeout: "15s"
HTTPServerReadHeaderTimeout: "15s"
HTTPServerWriteTimeout: "15s"
HTTPServerAddress: "127.0.0.1:9010"
HTTPServerPort: 4444

JwtToken:
  AccessSignKey: "hajihaji"
  AccessJWTExp: "168h"
  RefreshSignKey: ""
  RefreshExp: "720h"

Mongo:
  MongoURI: ""

V2rayAddress:
  MtnAddress: "mtn.fullspeedy.online"
  MtnXAddress: "mtnx.fullspeedy.online"
  MciAddress: "mci.fullspeedy.online"
  MciXAddress: "mcix.fullspeedy.online"
  WifiAddress: "wifi.fullspeedy.online"
  WifiXAddress: "wifix.fullspeedy.online"
  Port443: 443
  Port80: 80
  Port2053: 2053
  Port2083: 2083

GlobalTimeout: "5s"
