// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dep

import (
	"stockland/config"
	"stockland/pkg/client"
	"stockland/pkg/db/postgres_gorm_db"
	"stockland/pkg/jwt"
	"stockland/pkg/log"
	"stockland/service/product"
)

// Injectors from wire.go:

// initializeContainer is dependency injected form of having *service.Container
func InitializeContainer() (*service.Container, error) {
	clientClient := client.NewClient()
	configConfig := config.NewConfigFromViper()
	jwtJWT := jwt.NewJWT(configConfig)
	loggerLogger := logger.NewSLogger()
	db, err := postgres_gorm_db.NewPostgresConn(configConfig)
	if err != nil {
		return nil, err
	}
	container := service.NewContainer(clientClient, configConfig, jwtJWT, loggerLogger, db)
	return container, nil
}
